name: GUIDemoInputs
main: CKylin\GUIDemoInputs
version: 1.0.0
api: [1.0.0]
load: POSTWORLD
author: CKylin
commands:
 showgui:
  description: "..."
  usage: "/showgui"
  permission: GUIDemoInputs.cmd.main
permissions:
 GUIDemoInputs.cmd.main:
  description: "showgui"
  default: true
